apiVersion: v1
kind: Service
metadata:
  name: sample-python-service
spec:
  selector:
    app: sample-python
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python
spec:
  selector:
    matchLabels:
      app: sample-python
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-python
    spec:
      containers:
      - name: sample-python
        image: sample-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000